name: cipher_safety
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.3+3

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dart_nats: ^0.6.5
  shared_preferences: ^2.5.5
  permission_handler: ^12.0.1
  flutter_ringtone_player: ^4.0.0+4
  vibration: ^3.1.8
  torch_light: ^1.1.0
  volume_controller: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:

  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  remove_alpha_ios: true

  